namespace ChapterTool.Core.Diagnostics;

#pragma warning disable CS1591

/// <summary>
/// Components, formats, or data fields that can produce diagnostics.
/// </summary>
public enum ChapterDiagnosticSource
{
    AppendSource,
    ChapterIndex,
    ChapterPair,
    Chapters,
    ChapterText,
    ChapterTimestamp,
    CombineSource,
    ContainerHeader,
    CueFile,
    CueSyntax,
    Dependency,
    DependencyExecution,
    DependencyOutput,
    EmbeddedCue,
    EntryElement,
    ExportFormat,
    Expression,
    ExpressionCharacter,
    ExpressionComma,
    ExpressionFunction,
    ExpressionOperandBeforeParen,
    ExpressionOperator,
    ExpressionOperatorBeforeFunction,
    ExpressionOperatorBeforeParen,
    ExpressionParentheses,
    ExpressionTernaryColon,
    ExpressionTernaryCondition,
    ExpressionTernaryQuestion,
    ExpressionTernaryTrueExpression,
    ExpressionTime,
    ExpressionToken,
    Ffprobe,
    FfprobeOutput,
    FfprobeProcess,
    FlacEmbeddedCue,
    FrameRate,
    FrameText,
    Ifo,
    Importer,
    ImporterFallback,
    Input,
    LuaExpression,
    LuaExpressionReturn,
    LuaExpressionToken,
    Matroska,
    MatroskaChapters,
    MatroskaOutput,
    MatroskaProcess,
    MediaRead,
    Mp4File,
    Mp4Metadata,
    Mp4Path,
    Mp4Read,
    Mpls,
    NativeLibrary,
    OgmFirstLine,
    OrderShift,
    Parse,
    Path,
    PremiereMarkerList,
    Rows,
    Save,
    Segments,
    SelectionGroup,
    SelectionOption,
    Source,
    StandardOutput,
    Structure,
    TimecodeText,
    TimeText,
    WebVtt,
    WebVttCue,
    WebVttCueText,
    WebVttHeader,
    WebVttTimingSettings,
    Xml,
    XmlChapters,
    XmlRoot,
    XplChapters,
    XplParse
}

#pragma warning restore CS1591
