namespace ChapterTool.Wasm.Services;

/// <summary>
/// Browser-side UI strings for zh-CN / en-US / ja-JP.
/// Core diagnostic messages stay in their original form.
/// </summary>
public sealed class WasmLocalizer
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "ChapterTool",
        ["Action.Load"] = "Load",
        ["Action.Save"] = "Save",
        ["Action.Reload"] = "Reload",
        ["Action.AppendMpls"] = "Append MPLS…",
        ["Action.Preview"] = "Preview",
        ["Action.Refresh"] = "Refresh rows",
        ["Action.Settings"] = "Settings",
        ["Action.Log"] = "Log",
        ["Action.Close"] = "Close",
        ["Action.Clear"] = "Clear",
        ["Action.Cancel"] = "Cancel",
        ["Action.Apply"] = "Save",
        ["Action.RestoreDefaults"] = "Restore defaults",
        ["Action.Copy"] = "Copy",
        ["Action.Download"] = "Download",
        ["Action.LoadSample"] = "Load OGM sample",
        ["Action.BrowseTemplate"] = "Browse template…",
        ["Label.RoundFrames"] = "Round frames",
        ["Label.SaveAs"] = "Save as",
        ["Label.ChapterName"] = "Chapter name",
        ["Label.XmlLang"] = "XML lang",
        ["Label.OrderShift"] = "Order +",
        ["Label.Expression"] = "Expression",
        ["Label.UseExpression"] = "Use",
        ["Label.Clip"] = "Clip / playlist entry",
        ["Label.FrameRate"] = "Frame rate used for Frames column",
        ["Label.TemplateStatus"] = "Template",
        ["NameMode.AsIs"] = "As is",
        ["NameMode.Auto"] = "Auto generate",
        ["NameMode.Template"] = "Template",
        ["Grid.Number"] = "#",
        ["Grid.Time"] = "Time",
        ["Grid.Name"] = "Name",
        ["Grid.Frames"] = "Frames",
        ["Empty.Title"] = "No chapters loaded",
        ["Empty.Hint"] = "Load a file, drop one here, or load the sample to compute frames and expressions.",
        ["Status.Ready"] = "Ready — load a chapter file.",
        ["Status.Loading"] = "Loading…",
        ["Status.Appending"] = "Appending MPLS…",
        ["Status.LoadFailed"] = "Load failed.",
        ["Status.NothingToSave"] = "Nothing to save.",
        ["Status.SaveFailed"] = "Save failed.",
        ["Status.NoPreview"] = "Nothing to preview.",
        ["Status.PreviewFailed"] = "Preview failed.",
        ["Status.NoReload"] = "No previously loaded file to reload.",
        ["Status.CannotAppend"] = "Append MPLS is only available for an open MPLS session.",
        ["Status.AppendFailed"] = "Append failed.",
        ["Status.TemplateNotSelected"] = "No template file selected.",
        ["Status.TemplateLoaded"] = "Template loaded: {0}",
        ["Status.TemplateFailed"] = "Could not read template file.",
        ["Status.ZonesGenerated"] = "Generated zones for the selection.",
        ["Status.ZonesEmpty"] = "No zones generated.",
        ["Status.Shifted"] = "Shifted chapters forward by {0} frame(s).",
        ["Status.NoSelection"] = "Select one or more chapter rows first.",
        ["Status.NoRelatedMedia"] = "No related media references for the current clip.",
        ["Status.RelatedMediaNote"] = "Browser cannot open local media paths; references are shown for download/open when available.",
        ["Status.DropReady"] = "Drop a chapter file to load.",
        ["Status.DropEmpty"] = "Dropped file is empty.",
        ["Status.DropTooLarge"] = "File is too large (max 64 MB).",
        ["Status.DropBlocked"] = "Browser blocked reading the dropped file.",
        ["Status.SelectedRows"] = "Selected {0} row(s).",
        ["Status.Inserted"] = "Inserted a new chapter.",
        ["Status.Duplicated"] = "Duplicated row {0}.",
        ["Status.Deleted"] = "Deleted {0} row(s).",
        ["Status.CannotShift"] = "Frames to shift must be greater than zero.",
        ["Status.Loaded"] = "Loaded {0} chapter(s) from {1}.",
        ["Status.Appended"] = "Appended {0} MPLS segment(s) from {1}.",
        ["Status.SelectedClip"] = "Selected clip: {0}",
        ["Status.RestoredClips"] = "Restored separate clips.",
        ["Status.CombineFailed"] = "Could not combine clips.",
        ["Status.Combined"] = "Combined {0} clip(s).",
        ["Status.CombinedDone"] = "Combined clips.",
        ["Status.ChangeFpsFailed"] = "Could not change frame rate.",
        ["Status.ChangedFps"] = "Changed frame rate from {0:0.###} to {1:0.###}.",
        ["Status.ChangedFpsTo"] = "Changed frame rate to {0}.",
        ["Status.RowsRefreshed"] = "Rows refreshed · {0} fps · {1} row(s)",
        ["Status.Previewed"] = "Preview {0} · {1:N0} chars",
        ["Status.Saved"] = "Saved {0} → {1}",
        ["Status.ExpressionApplied"] = "Expression applied · {0} fps · {1} row(s)",
        ["Status.FramesUpdated"] = "Frames updated · {0} fps · {1} row(s)",
        ["Menu.Select"] = "Select row",
        ["Menu.Insert"] = "Insert before",
        ["Menu.Duplicate"] = "Duplicate",
        ["Menu.CopyRow"] = "Copy row",
        ["Menu.CopyName"] = "Copy name",
        ["Menu.CopyZones"] = "Copy --zones",
        ["Menu.Delete"] = "Delete",
        ["Menu.Preview"] = "Preview",
        ["Menu.Zones"] = "Zones",
        ["Menu.ForwardTranslation"] = "Forward translation…",
        ["Menu.RelatedMedia"] = "Open related media…",
        ["Menu.Combine"] = "Combine clips",
        ["Menu.Split"] = "Split combined clips",
        ["Menu.ChangeFps"] = "Change FPS",
        ["Modal.LogTitle"] = "Activity log",
        ["Modal.LogEmpty"] = "No activity yet.",
        ["Modal.SettingsTitle"] = "Settings",
        ["Modal.PreviewTitle"] = "Preview",
        ["Modal.ForwardTitle"] = "Forward translation",
        ["Modal.RelatedTitle"] = "Related media",
        ["Modal.Frames"] = "Frames to shift",
        ["Modal.ApplyShift"] = "Apply",
        ["Settings.General"] = "General",
        ["Settings.Tools"] = "External tools",
        ["Settings.Output"] = "Output defaults",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.About"] = "About",
        ["Settings.UiLanguage"] = "UI language",
        ["Settings.SaveDirectory"] = "Save directory",
        ["Settings.SaveDirectoryValue"] = "Browser default download folder",
        ["Settings.SaveDirectoryNote"] = "The browser controls the download directory. UI language selection is stored with the settings snapshot.",
        ["Settings.ToolUnavailable"] = "Unavailable in browser WASM",
        ["Settings.ToolNote"] = "Native executable paths are not available in this browser workspace.",
        ["Settings.ValidateTools"] = "Validate tools",
        ["Settings.DefaultSaveFormat"] = "Default save format",
        ["Settings.DefaultXmlLanguage"] = "Default XML language",
        ["Settings.TextEncoding"] = "Text encoding",
        ["Settings.EmitBom"] = "Emit BOM",
        ["Settings.EmitBomLabel"] = "Include byte order mark in text downloads",
        ["Settings.Tolerance"] = "Frame accuracy tolerance",
        ["Settings.Preset"] = "Preset",
        ["Settings.Preview"] = "Preview",
        ["Settings.UiFont"] = "UI font",
        ["Settings.MonoFont"] = "Monospace font",
        ["Settings.AboutBody"] = "ChapterTool Core browser workspace for importing, editing, projecting and exporting chapter data in WebAssembly.",
        ["Settings.AboutRuntime"] = "Blazor WebAssembly · .NET 10",
        ["Settings.AboutLicense"] = "Core functionality is provided under the project license.",
        ["Tool.mkvtoolnix"] = "MkvToolnix path",
        ["Tool.eac3to"] = "Eac3to path",
        ["Tool.ffprobe"] = "Ffprobe path",
        ["Tool.ffmpeg"] = "Ffmpeg path",
        ["Title.Load"] = "Load chapter file",
        ["Title.Save"] = "Export with current options and download",
        ["Title.Preview"] = "Preview projected export text",
        ["Title.Refresh"] = "Refresh grid from current options",
        ["Title.Expression"] = "Lua expression over chapter time, e.g. t + 1 or t * 25 / 24",
        ["Copy.Row"] = "Copied row(s) to clipboard.",
        ["Copy.Name"] = "Copied chapter name(s) to clipboard.",
        ["Copy.Zones"] = "Copied --zones to clipboard.",
        ["Copy.Preview"] = "Copied preview text to clipboard.",
        ["Related.Relative"] = "Relative path",
        ["Related.Absolute"] = "Absolute path",
        ["Related.BrowserLimit"] = "Local absolute paths cannot be opened by the browser. Relative paths are informational only unless the host serves them."
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "ChapterTool",
        ["Action.Load"] = "加载",
        ["Action.Save"] = "保存",
        ["Action.Reload"] = "重新加载",
        ["Action.AppendMpls"] = "追加 MPLS…",
        ["Action.Preview"] = "预览",
        ["Action.Refresh"] = "刷新行",
        ["Action.Settings"] = "设置",
        ["Action.Log"] = "日志",
        ["Action.Close"] = "关闭",
        ["Action.Clear"] = "清空",
        ["Action.Cancel"] = "取消",
        ["Action.Apply"] = "保存",
        ["Action.RestoreDefaults"] = "恢复默认",
        ["Action.Copy"] = "复制",
        ["Action.Download"] = "下载",
        ["Action.LoadSample"] = "加载 OGM 示例",
        ["Action.BrowseTemplate"] = "浏览模板…",
        ["Label.RoundFrames"] = "帧取整",
        ["Label.SaveAs"] = "保存为",
        ["Label.ChapterName"] = "章节名",
        ["Label.XmlLang"] = "XML 语言",
        ["Label.OrderShift"] = "序号 +",
        ["Label.Expression"] = "表达式",
        ["Label.UseExpression"] = "启用",
        ["Label.Clip"] = "片段 / 播放列表项",
        ["Label.FrameRate"] = "用于帧列的帧率",
        ["Label.TemplateStatus"] = "模板",
        ["NameMode.AsIs"] = "保持原名",
        ["NameMode.Auto"] = "自动生成",
        ["NameMode.Template"] = "模板",
        ["Grid.Number"] = "#",
        ["Grid.Time"] = "时间",
        ["Grid.Name"] = "名称",
        ["Grid.Frames"] = "帧",
        ["Empty.Title"] = "尚未加载章节",
        ["Empty.Hint"] = "加载文件、拖放到此处，或加载示例以计算帧与表达式。",
        ["Status.Ready"] = "就绪 — 请加载章节文件。",
        ["Status.Loading"] = "加载中…",
        ["Status.Appending"] = "正在追加 MPLS…",
        ["Status.LoadFailed"] = "加载失败。",
        ["Status.NothingToSave"] = "没有可保存的内容。",
        ["Status.SaveFailed"] = "保存失败。",
        ["Status.NoPreview"] = "没有可预览的内容。",
        ["Status.PreviewFailed"] = "预览失败。",
        ["Status.NoReload"] = "没有可重新加载的文件。",
        ["Status.CannotAppend"] = "仅在已打开的 MPLS 会话中可追加 MPLS。",
        ["Status.AppendFailed"] = "追加失败。",
        ["Status.TemplateNotSelected"] = "未选择模板文件。",
        ["Status.TemplateLoaded"] = "已加载模板：{0}",
        ["Status.TemplateFailed"] = "无法读取模板文件。",
        ["Status.ZonesGenerated"] = "已为所选行生成 zones。",
        ["Status.ZonesEmpty"] = "未生成 zones。",
        ["Status.Shifted"] = "已将章节前移 {0} 帧。",
        ["Status.NoSelection"] = "请先选择一个或多个章节行。",
        ["Status.NoRelatedMedia"] = "当前片段没有关联媒体引用。",
        ["Status.RelatedMediaNote"] = "浏览器无法打开本地媒体路径；可用时仅以下载/链接方式展示引用。",
        ["Status.DropReady"] = "松开以加载章节文件。",
        ["Status.DropEmpty"] = "拖放的文件为空。",
        ["Status.DropTooLarge"] = "文件过大（最大 64 MB）。",
        ["Status.DropBlocked"] = "浏览器禁止读取该拖放文件。",
        ["Status.SelectedRows"] = "已选择 {0} 行。",
        ["Status.Inserted"] = "已插入新章节。",
        ["Status.Duplicated"] = "已复制第 {0} 行。",
        ["Status.Deleted"] = "已删除 {0} 行。",
        ["Status.CannotShift"] = "要前移的帧数必须大于零。",
        ["Status.Loaded"] = "已从 {1} 加载 {0} 个章节。",
        ["Status.Appended"] = "已从 {1} 追加 {0} 个 MPLS 片段。",
        ["Status.SelectedClip"] = "已选择剪辑：{0}",
        ["Status.RestoredClips"] = "已恢复分开的剪辑。",
        ["Status.CombineFailed"] = "无法合并剪辑。",
        ["Status.Combined"] = "已合并 {0} 个剪辑。",
        ["Status.CombinedDone"] = "已合并剪辑。",
        ["Status.ChangeFpsFailed"] = "无法更改帧率。",
        ["Status.ChangedFps"] = "已将帧率从 {0:0.###} 更改为 {1:0.###}。",
        ["Status.ChangedFpsTo"] = "已将帧率更改为 {0}。",
        ["Status.RowsRefreshed"] = "已刷新行 · {0} fps · {1} 行",
        ["Status.Previewed"] = "预览 {0} · {1:N0} 个字符",
        ["Status.Saved"] = "已保存 {0} → {1}",
        ["Status.ExpressionApplied"] = "已应用表达式 · {0} fps · {1} 行",
        ["Status.FramesUpdated"] = "已更新帧 · {0} fps · {1} 行",
        ["Menu.Select"] = "选择行",
        ["Menu.Insert"] = "在此之前插入",
        ["Menu.Duplicate"] = "复制行",
        ["Menu.CopyRow"] = "复制行内容",
        ["Menu.CopyName"] = "复制名称",
        ["Menu.CopyZones"] = "复制 --zones",
        ["Menu.Delete"] = "删除",
        ["Menu.Preview"] = "预览",
        ["Menu.Zones"] = "Zones",
        ["Menu.ForwardTranslation"] = "前移翻译…",
        ["Menu.RelatedMedia"] = "打开关联媒体…",
        ["Menu.Combine"] = "合并片段",
        ["Menu.Split"] = "拆分已合并片段",
        ["Menu.ChangeFps"] = "更改帧率",
        ["Modal.LogTitle"] = "活动日志",
        ["Modal.LogEmpty"] = "暂无活动。",
        ["Modal.SettingsTitle"] = "设置",
        ["Modal.PreviewTitle"] = "预览",
        ["Modal.ForwardTitle"] = "前移翻译",
        ["Modal.RelatedTitle"] = "关联媒体",
        ["Modal.Frames"] = "前移帧数",
        ["Modal.ApplyShift"] = "应用",
        ["Settings.General"] = "常规",
        ["Settings.Tools"] = "外部工具",
        ["Settings.Output"] = "输出默认值",
        ["Settings.Appearance"] = "外观",
        ["Settings.About"] = "关于",
        ["Settings.UiLanguage"] = "界面语言",
        ["Settings.SaveDirectory"] = "保存目录",
        ["Settings.SaveDirectoryValue"] = "浏览器默认下载文件夹",
        ["Settings.SaveDirectoryNote"] = "下载目录由浏览器控制。界面语言会写入设置快照。",
        ["Settings.ToolUnavailable"] = "浏览器 WASM 不可用",
        ["Settings.ToolNote"] = "本浏览器工作台无法配置本机可执行文件路径。",
        ["Settings.ValidateTools"] = "验证工具",
        ["Settings.DefaultSaveFormat"] = "默认保存格式",
        ["Settings.DefaultXmlLanguage"] = "默认 XML 语言",
        ["Settings.TextEncoding"] = "文本编码",
        ["Settings.EmitBom"] = "输出 BOM",
        ["Settings.EmitBomLabel"] = "在文本下载中包含字节顺序标记",
        ["Settings.Tolerance"] = "帧精度容差",
        ["Settings.Preset"] = "预设",
        ["Settings.Preview"] = "预览",
        ["Settings.UiFont"] = "界面字体",
        ["Settings.MonoFont"] = "等宽字体",
        ["Settings.AboutBody"] = "ChapterTool Core 浏览器工作台：在 WebAssembly 中导入、编辑、投影并导出章节数据。",
        ["Settings.AboutRuntime"] = "Blazor WebAssembly · .NET 10",
        ["Settings.AboutLicense"] = "核心功能遵循项目许可证提供。",
        ["Tool.mkvtoolnix"] = "MkvToolnix 路径",
        ["Tool.eac3to"] = "Eac3to 路径",
        ["Tool.ffprobe"] = "Ffprobe 路径",
        ["Tool.ffmpeg"] = "Ffmpeg 路径",
        ["Title.Load"] = "加载章节文件",
        ["Title.Save"] = "按当前选项导出并下载",
        ["Title.Preview"] = "预览投影后的导出文本",
        ["Title.Refresh"] = "按当前选项刷新表格",
        ["Title.Expression"] = "基于章节时间的 Lua 表达式，例如 t + 1 或 t * 25 / 24",
        ["Copy.Row"] = "已复制行内容到剪贴板。",
        ["Copy.Name"] = "已复制章节名称到剪贴板。",
        ["Copy.Zones"] = "已复制 --zones 到剪贴板。",
        ["Copy.Preview"] = "已复制预览文本到剪贴板。",
        ["Related.Relative"] = "相对路径",
        ["Related.Absolute"] = "绝对路径",
        ["Related.BrowserLimit"] = "浏览器无法打开本地绝对路径。相对路径仅供参考，除非主机实际提供这些资源。"
    };

    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "ChapterTool",
        ["Action.Load"] = "読み込み",
        ["Action.Save"] = "保存",
        ["Action.Reload"] = "再読み込み",
        ["Action.AppendMpls"] = "MPLS を追加…",
        ["Action.Preview"] = "プレビュー",
        ["Action.Refresh"] = "行を更新",
        ["Action.Settings"] = "設定",
        ["Action.Log"] = "ログ",
        ["Action.Close"] = "閉じる",
        ["Action.Clear"] = "クリア",
        ["Action.Cancel"] = "キャンセル",
        ["Action.Apply"] = "保存",
        ["Action.RestoreDefaults"] = "既定に戻す",
        ["Action.Copy"] = "コピー",
        ["Action.Download"] = "ダウンロード",
        ["Action.LoadSample"] = "OGM サンプルを読み込む",
        ["Action.BrowseTemplate"] = "テンプレートを参照…",
        ["Label.RoundFrames"] = "フレーム丸め",
        ["Label.SaveAs"] = "形式",
        ["Label.ChapterName"] = "チャプター名",
        ["Label.XmlLang"] = "XML 言語",
        ["Label.OrderShift"] = "番号 +",
        ["Label.Expression"] = "式",
        ["Label.UseExpression"] = "使用",
        ["Label.Clip"] = "クリップ / プレイリスト項目",
        ["Label.FrameRate"] = "Frames 列に使うフレームレート",
        ["Label.TemplateStatus"] = "テンプレート",
        ["NameMode.AsIs"] = "そのまま",
        ["NameMode.Auto"] = "自動生成",
        ["NameMode.Template"] = "テンプレート",
        ["Grid.Number"] = "#",
        ["Grid.Time"] = "時刻",
        ["Grid.Name"] = "名前",
        ["Grid.Frames"] = "フレーム",
        ["Empty.Title"] = "チャプターがありません",
        ["Empty.Hint"] = "ファイルを読み込む、ここにドロップする、またはサンプルを読み込んでフレームと式を計算します。",
        ["Status.Ready"] = "準備完了 — チャプターファイルを読み込んでください。",
        ["Status.Loading"] = "読み込み中…",
        ["Status.Appending"] = "MPLS を追加中…",
        ["Status.LoadFailed"] = "読み込みに失敗しました。",
        ["Status.NothingToSave"] = "保存する内容がありません。",
        ["Status.SaveFailed"] = "保存に失敗しました。",
        ["Status.NoPreview"] = "プレビューする内容がありません。",
        ["Status.PreviewFailed"] = "プレビューに失敗しました。",
        ["Status.NoReload"] = "再読み込みできるファイルがありません。",
        ["Status.CannotAppend"] = "MPLS 追加は開いている MPLS セッションでのみ利用できます。",
        ["Status.AppendFailed"] = "追加に失敗しました。",
        ["Status.TemplateNotSelected"] = "テンプレートファイルが選択されていません。",
        ["Status.TemplateLoaded"] = "テンプレートを読み込みました: {0}",
        ["Status.TemplateFailed"] = "テンプレートファイルを読めませんでした。",
        ["Status.ZonesGenerated"] = "選択行の zones を生成しました。",
        ["Status.ZonesEmpty"] = "zones は生成されませんでした。",
        ["Status.Shifted"] = "チャプターを {0} フレーム前へ移動しました。",
        ["Status.NoSelection"] = "先に 1 行以上のチャプター行を選択してください。",
        ["Status.NoRelatedMedia"] = "現在のクリップに関連メディア参照がありません。",
        ["Status.RelatedMediaNote"] = "ブラウザはローカルメディアパスを開けません。可能な場合のみダウンロード/リンクとして表示します。",
        ["Status.DropReady"] = "チャプターファイルをドロップして読み込みます。",
        ["Status.DropEmpty"] = "ドロップされたファイルが空です。",
        ["Status.DropTooLarge"] = "ファイルが大きすぎます（最大 64 MB）。",
        ["Status.DropBlocked"] = "ブラウザがドロップファイルの読み取りを拒否しました。",
        ["Status.SelectedRows"] = "{0} 行を選択しました。",
        ["Status.Inserted"] = "新しいチャプターを挿入しました。",
        ["Status.Duplicated"] = "{0} 行目を複製しました。",
        ["Status.Deleted"] = "{0} 行を削除しました。",
        ["Status.CannotShift"] = "移動するフレーム数は 0 より大きくしてください。",
        ["Status.Loaded"] = "{1} から {0} 個のチャプターを読み込みました。",
        ["Status.Appended"] = "{1} から {0} 個の MPLS セグメントを追加しました。",
        ["Status.SelectedClip"] = "クリップを選択しました: {0}",
        ["Status.RestoredClips"] = "分割されたクリップに戻しました。",
        ["Status.CombineFailed"] = "クリップを結合できませんでした。",
        ["Status.Combined"] = "{0} 個のクリップを結合しました。",
        ["Status.CombinedDone"] = "クリップを結合しました。",
        ["Status.ChangeFpsFailed"] = "フレームレートを変更できませんでした。",
        ["Status.ChangedFps"] = "フレームレートを {0:0.###} から {1:0.###} に変更しました。",
        ["Status.ChangedFpsTo"] = "フレームレートを {0} に変更しました。",
        ["Status.RowsRefreshed"] = "行を更新しました · {0} fps · {1} 行",
        ["Status.Previewed"] = "プレビュー {0} · {1:N0} 文字",
        ["Status.Saved"] = "{0} を保存しました → {1}",
        ["Status.ExpressionApplied"] = "式を適用しました · {0} fps · {1} 行",
        ["Status.FramesUpdated"] = "フレームを更新しました · {0} fps · {1} 行",
        ["Menu.Select"] = "行を選択",
        ["Menu.Insert"] = "前に挿入",
        ["Menu.Duplicate"] = "複製",
        ["Menu.CopyRow"] = "行をコピー",
        ["Menu.CopyName"] = "名前をコピー",
        ["Menu.CopyZones"] = "--zones をコピー",
        ["Menu.Delete"] = "削除",
        ["Menu.Preview"] = "プレビュー",
        ["Menu.Zones"] = "Zones",
        ["Menu.ForwardTranslation"] = "前方シフト…",
        ["Menu.RelatedMedia"] = "関連メディアを開く…",
        ["Menu.Combine"] = "クリップを結合",
        ["Menu.Split"] = "結合クリップを分割",
        ["Menu.ChangeFps"] = "FPS を変更",
        ["Modal.LogTitle"] = "アクティビティログ",
        ["Modal.LogEmpty"] = "まだ記録がありません。",
        ["Modal.SettingsTitle"] = "設定",
        ["Modal.PreviewTitle"] = "プレビュー",
        ["Modal.ForwardTitle"] = "前方シフト",
        ["Modal.RelatedTitle"] = "関連メディア",
        ["Modal.Frames"] = "シフトするフレーム数",
        ["Modal.ApplyShift"] = "適用",
        ["Settings.General"] = "一般",
        ["Settings.Tools"] = "外部ツール",
        ["Settings.Output"] = "出力の既定値",
        ["Settings.Appearance"] = "外観",
        ["Settings.About"] = "情報",
        ["Settings.UiLanguage"] = "UI 言語",
        ["Settings.SaveDirectory"] = "保存先",
        ["Settings.SaveDirectoryValue"] = "ブラウザの既定ダウンロードフォルダー",
        ["Settings.SaveDirectoryNote"] = "ダウンロード先はブラウザが管理します。UI 言語は設定スナップショットに保存されます。",
        ["Settings.ToolUnavailable"] = "ブラウザ WASM では利用不可",
        ["Settings.ToolNote"] = "このブラウザワークスペースではネイティブ実行ファイルのパスを設定できません。",
        ["Settings.ValidateTools"] = "ツールを検証",
        ["Settings.DefaultSaveFormat"] = "既定の保存形式",
        ["Settings.DefaultXmlLanguage"] = "既定の XML 言語",
        ["Settings.TextEncoding"] = "テキストエンコーディング",
        ["Settings.EmitBom"] = "BOM を出力",
        ["Settings.EmitBomLabel"] = "テキストダウンロードに BOM を含める",
        ["Settings.Tolerance"] = "フレーム精度の許容誤差",
        ["Settings.Preset"] = "プリセット",
        ["Settings.Preview"] = "プレビュー",
        ["Settings.UiFont"] = "UI フォント",
        ["Settings.MonoFont"] = "等幅フォント",
        ["Settings.AboutBody"] = "ChapterTool Core のブラウザワークスペース。WebAssembly でチャプターの読み込み・編集・投影・書き出しを行います。",
        ["Settings.AboutRuntime"] = "Blazor WebAssembly · .NET 10",
        ["Settings.AboutLicense"] = "コア機能はプロジェクトのライセンスに従って提供されます。",
        ["Tool.mkvtoolnix"] = "MkvToolnix パス",
        ["Tool.eac3to"] = "Eac3to パス",
        ["Tool.ffprobe"] = "Ffprobe パス",
        ["Tool.ffmpeg"] = "Ffmpeg パス",
        ["Title.Load"] = "チャプターファイルを読み込む",
        ["Title.Save"] = "現在のオプションで書き出してダウンロード",
        ["Title.Preview"] = "投影後の書き出しテキストをプレビュー",
        ["Title.Refresh"] = "現在のオプションでグリッドを更新",
        ["Title.Expression"] = "チャプター時刻に対する Lua 式。例: t + 1 または t * 25 / 24",
        ["Copy.Row"] = "行をクリップボードにコピーしました。",
        ["Copy.Name"] = "チャプター名をクリップボードにコピーしました。",
        ["Copy.Zones"] = "--zones をクリップボードにコピーしました。",
        ["Copy.Preview"] = "プレビューテキストをクリップボードにコピーしました。",
        ["Related.Relative"] = "相対パス",
        ["Related.Absolute"] = "絶対パス",
        ["Related.BrowserLimit"] = "ブラウザはローカル絶対パスを開けません。ホストが提供しない限り、相対パスは参考情報のみです。"
    };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Catalog =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en-US"] = English,
            ["zh-CN"] = Chinese,
            ["ja-JP"] = Japanese
        };

    public string Culture { get; private set; } = "en-US";

    public event Action? CultureChanged;

    public void SetCulture(string culture)
    {
        var normalized = Normalize(culture);
        if (string.Equals(Culture, normalized, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        Culture = normalized;
        CultureChanged?.Invoke();
    }

    public string T(string key)
    {
        if (Catalog.TryGetValue(Culture, out var table) && table.TryGetValue(key, out var value))
        {
            return value;
        }

        if (English.TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }

    public string Format(string key, params object[] args) =>
        string.Format(System.Globalization.CultureInfo.CurrentCulture, T(key), args);

    public IReadOnlyList<string> ChapterNameModes =>
    [
        T("NameMode.AsIs"),
        T("NameMode.Auto"),
        T("NameMode.Template")
    ];

    public IReadOnlyList<string> SettingsTabs =>
    [
        T("Settings.General"),
        T("Settings.Tools"),
        T("Settings.Output"),
        T("Settings.Appearance"),
        T("Settings.About")
    ];

    public static string Normalize(string? culture) =>
        culture?.Trim() switch
        {
            "zh-CN" or "zh" or "zh-Hans" => "zh-CN",
            "ja-JP" or "ja" => "ja-JP",
            _ => "en-US"
        };
}
